version: '2'

services:

  nginx:
    image: nginx:latest
    ports:
      - 8181:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php

  frontend:
    build: ./docker/node/
    environment:
      - NODE_ENV=production
    ports:
      - 8182:8080
    volumes:
      - ./frontend:/app
        
  php:
    build: ./docker/php/
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
        - database

    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  database:
        image: mysql:5.7
        environment:
          - "MYSQL_ROOT_PASSWORD=alegraprueba"
          - "MYSQL_DATABASE=alegra"
        volumes:
          - ./dbdata:/var/lib/mysql
        ports:
          - "33065:3306"
